Develop
still-coding/labs pull request #1
Opened 2024-02-28 19:05 UTC by Ol333

В 1 лабе по C изменения примера и блок-схемы, позволяющие избавится от импорта math.h
В 8 лабе по С изменения в примера делают чуть более очевидным вывод от нажатия управляющих символов
Остальное - опечатки, если я ничего не забыла

2024-03-02 17:14 UTC, still-coding requested changes
В целом ок, замечания написал, докрутите и вмёржим

2024-03-02 17:14 UTC, still-coding commented on static/images/c_lab01.svg
Новая свгшка не поддерживает тёмную тему - почините

2024-03-02 17:14 UTC, still-coding commented on content/c/lab08.md
> +    }
Может сделаем попроще?
```c
while (1)
{
    char a = mygetch();
    printf("%c %d\n", a, a);
}
```

2024-03-02 17:14 UTC, still-coding commented on content/python/exam.md
А зачем вопросы выносить сюда, если они в extras уже лежат?

2024-03-06 12:58 UTC, Ol333 commented on content/python/exam.md
Это случайно

2024-03-06 12:58 UTC, Ol333 commented on content/c/lab08.md
> +    }
Изменила

2024-03-06 13:03 UTC, Ol333 commented on static/images/c_lab01.svg
Проверила на своем сайте, должно работать

2024-03-06 21:38 UTC, still-coding requested changes

2024-03-06 21:38 UTC, still-coding commented on static/images/c_lab01.svg
теперь она не поддерживает светлую тему 😂

2024-03-07 17:04 UTC, Ol333 commented on static/images/c_lab01.svg
Если все, внезапно, заработало, то замечу еще, что Прог ссылается на эту блок-схему, а пример кода там я не изменяла

2024-03-07 18:20 UTC, still-coding commented on static/images/c_lab01.svg
надо поменять тоже, получается

2024-03-09 16:55 UTC, merged